spring:
  jackson:
    serialization:
      INDENT_OUTPUT: 'true'
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:razei
server:
  servlet:
    contextPath: /api/v1

jwt:
  secret: patocabraraton